# Generated by Django 5.0.7 on 2024-08-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0006_alter_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
