# Generated by Django 5.0.7 on 2024-08-10 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0009_classify_product_classify'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='classify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='quoteapp.classify'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='quoteapp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='classify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='quoteapp.classify'),
        ),
    ]
